sensu-plugins/sensu-plugins-process-checks

bin/process-uptime-metrics.sh
Although there was a pre-existing plugin for checking whether a process is running or not, there was no plugin to track the uptime of a process over a prolonged interval of time. This newly written plugin uses the same logic which was used to check whether the process is running or not, with an addition that it instead echoes a metric with a value of 1 or 0 depending on the running state of the process, in graphite plaintext metric format i.e." metric_name metric_value timestamp".
=> New plugin to generate process uptime metrics

bin/check-cmd.rb
I was getting the following on my system
```
Check failed to run: undefined method `exitstatus' for nil:NilClass, ["/etc/sensu/plugins/check-cmd.rb:58:in `acquire_cmd_status'", "/etc/sensu/plugins/check-cmd.rb:76:in `run'", "/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugin-1.1.0/lib/sensu-plugin/cli.rb:56:in `block in <class:CLI>'"]
```
Once I change the gem to `English` the error went away
=> Gem name appears to be case sensitive

CHANGELOG.md, bin/metrics-processes-threads-count.rb
Default scheme "system" is not best... And it's behaviour different than most of metrics.
=> Fix default scheme to include hostname

CHANGELOG.md, bin/metrics-processes-threads-count.rb
6bbbc22de454d94192ed7393d7b767071f3d73fa introduced a default scheme by
using `Socket.gethostname` to use the system's hostname.  However,
Socket was not required here, resulting in errors.
=> Require Socket

bin/check-process.rb
Fixed sensu-community-plugins issues #802.
Default is set to ASCII-8BIT instead of US-ASCII to handle all characters even if it is not the right encoding (unicode). It allows check-procs.rb to not generate exception even if encoding is unicode.
=> Added encoding option/Set default to ASCII-8BIT

bin/check-process.rb
check-procs failed on supervised server. The correct binary name was check-process.rb
=> Fix binary name in usage documentation

CHANGELOG.md, bin/check-process-restart.rb, bin/check-threads-count.rb, bin/metrics-processes-threads-count.rb, sensu-plugins-process-checks.gemspec
- check-process-restart.rb is a very useful plugin for checking when a process needs to be restarted (such as after a critical security update to OpenSSL). However, it currently only supports Debian's **checkrestart** script and not Red Hat's **needs-restarting** script. Adding this functionality should provide support for Red Hat Enterprise Linux, CentOS, Amazon Linux, Scientific Linux, Oracle Linux, etc.
- Tested on CentOS 6, CentOS 7 and Amazon Linux.
=> Added support for Red Hat "needs-restarting" script to check-process-restart.rb

.travis.yml, Rakefile, sensu-plugins-process-checks.gemspec
This PR removes Ruby 1.9.3 support, and adds support for testing under Ruby 2.3.0, per the Sensu Plugins policy: 
> Ruby 1.9.3 (EOL): Linting is not done against it, and 1.9.3 will be supported where possible till Feb 2016 which is one year after EOL and 2 years after EOL was announced.
Adds incompatibility with Ruby version < 2.0.0
=> Remove Ruby 1.9.3 support; add Ruby 2.3.0 support

bin/metrics-per-process.py
Possible solution to issue [sensu-plugins-process-checks/issues/25](https://github.com/sensu-plugins/sensu-plugins-process-checks/issues/25)
Additional exception handling in `find_pids_from_name`
Tested on Python 2.7, not sure if it would work with Python 3
=> OSError exception handling

CHANGELOG.md, bin/check-process-restart.rb
We need to send a particular arg to checkrestart to filter out some
false positives.
This change allows for any additional args to be passed through - rather
than restricting to the current known args. We have allowed it for
checkrestart and the needs-restarting tool since we don't know for
sure what options needs-restarting can take.
Have also appeased rubocop in the command status checking.
=> Allow additional args to be passed to underlying tools

CHANGELOG.md, bin/check-process.rb
Addressing #23 . 
I encountered the same issue.
If pid file is specified, it is expected that the pid file must exist and contain pid to match. If pid file becomes non-existent, it very likely means that the monitored process cease to run (or the check should be treated as 'fail' because the pid file given is invalid) and check-process.rb check is expected to return CRITICAL rather than UNKNOWN. 
Technically, none.
=> check-process.rb: return CRITICAL if pid file is specified and does not exist

CHANGELOG.md, bin/check-process.rb
Example useage:
crit:
```
$ ./bin/check-process.rb -p 'slack' --cpu-utilization 2 --critical-under 0 --warn-under 0 --critical-over 0
CheckProcess CRITICAL: Found 1 matching processes; cmd /slack/; cpu > 2.0
```
ok:
```
$ ./bin/check-process.rb -p 'slack' --cpu-utilization 5 --critical-under 0 --warn-under 0 --critical-over 0
CheckProcess OK: Found 0 matching processes; cmd /slack/; cpu > 5.0
```
#36 
Make the code do what it thinks it's doing.
None, only tested linux unknown if bsd is different.
=> fixes #36 by renaming flag to actually alert based on the data it is pulling.

CHANGELOG.md, README.md, bin/metrics-per-process.rb, bin/metrics-process-uptime.rb
Adds two binstubs for the two non-Ruby scripts, `metrics-per-process.py` and `metrics-processes-threads-count.rb`.
=> Add binstubs for non-Ruby scripts

CHANGELOG.md, bin/metrics-per-process.py
Allows the metrics-per-process.py check to work in Python 2.6 environments by falling back to importing the Counter module from the backport_collections library.
None.
=> Add Python 2.6 support for metrics-per-process.py

CHANGELOG.md, bin/metrics-per-process.py
psutil's `memory_info_ex()` method was deprecated in their 4.0.0 release. This uses the updated `memory_info()` method in 4.0.0+, and the old method in previous versions, to eliminate deprecation notice warnings from the check.
None.
=> Use memory_info() instead of deprecated memory_info_ex() in metrics-per-process.py

CHANGELOG.md, bin/metrics-per-process.py
Implements #43. Adds a command line option to `metrics-per-process.py` to filter with a regexp the stats to output. Prints everything by default for backward compatibility. The stats that are filtered out are not queried, which avoids getting permission errors for stats that are not required.
- N/A Binstubs are created if needed
- N/A RuboCop passes
- N/A Existing tests pass
=> Add filter for stats name

CHANGELOG.md, bin/check-threads-count.rb, bin/metrics-processes-threads-count.rb, sensu-plugins-process-checks.gemspec, test/check-threads-count_spec.rb, test/metrics-processes-threads-count_spec.rb
We previously checked if `sys-proctable` was greater than `0.9.8` when it was originally introduced in https://github.com/sensu-plugins/sensu-plugins-process-checks/commit/32044984dcb647ff63260435ebfd3d96894a26a0#diff-681f43ba752e5217d82b23a247fd5c79 it was `0.9.6` which would have fit this condition. We are currently requiring `0.9.8` which makes this check of no real value. We are now requiring `~> 1.1`.
On top of that I am not sure the [logic](https://github.com/sensu-plugins/sensu-plugins-process-checks/blob/2.5.0/bin/check-threads-count.rb#L89-L91) actually was ever correct but I don't care enough to check if that is right as it is now irrelevant.
Signed-off-by: Ben Abrams <me@benabrams.it>
fixes #54 
Remove bitrot code and solve #54 at the same time.
:man_shrugging:
=> remove checks that do not actually make sense anymore

CHANGELOG.md, bin/metrics-per-process.py
I have use cases for metrics-per-process.py where there is several processes to aggregate (so pid file is not an option) and these processes run on the same executable as other unrelated processes (so finding by name is not an option either). A typical example is several services running on python or ruby. Searching processes by name will catch too many of them.
A way to solve this is to differentiate the processes by the user running them (it is common that a service is run by its own user).
This PR adds an option to metrics-per-process.py to find PIDs by the name of the user running the process. The user running the process is determined by inspecting the owner of the proc directory of the process.
Here is a gist with the output of a few test runs: …
=> Add option to metrics-per-process.py to find PIDs by user

bin/metrics-ipcs.rb
found is initialized to false and no condition sets it to true, consequently the checks always exits as critical.
**Is this in reference to an existing issue?**
No.
=> fix check always returning critical

sensu-plugins-process-checks.gemspec
Fix https://github.com/sensu-plugins/sensu-plugins-process-checks/issues/112
english 0.6.3 removed, upgrade to 0.7.0 solving the issue.
```
[root@foo001 ~]# /opt/sensu/embedded/bin/gem install -v 4.1.0 --no-rdoc --no-ri sensu-plugins-process-checks
ERROR:  Could not find a valid gem 'english' (= 0.6.3) in any repository
ERROR:  Possible alternatives: english
```
**Is this in reference to an existing issue?**
Yes
Fix #112
=> Fix dependencies issue on english
